//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gdocxEntities : DbContext
    {
        public gdocxEntities()
            : base("name=gdocxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<p_dependencia> p_dependencia { get; set; }
        public virtual DbSet<p_estado> p_estado { get; set; }
        public virtual DbSet<p_organizacion> p_organizacion { get; set; }
        public virtual DbSet<p_proyecto> p_proyecto { get; set; }
        public virtual DbSet<p_recurso> p_recurso { get; set; }
        public virtual DbSet<p_serie> p_serie { get; set; }
        public virtual DbSet<p_subdependencia> p_subdependencia { get; set; }
        public virtual DbSet<p_subserie> p_subserie { get; set; }
        public virtual DbSet<p_tipodoc> p_tipodoc { get; set; }
        public virtual DbSet<p_tipoitem> p_tipoitem { get; set; }
        public virtual DbSet<p_tiporesp> p_tiporesp { get; set; }
        public virtual DbSet<p_usuario> p_usuario { get; set; }
        public virtual DbSet<p_usuario_perfil> p_usuario_perfil { get; set; }
        public virtual DbSet<t_borrar_archivos> t_borrar_archivos { get; set; }
        public virtual DbSet<t_carpeta> t_carpeta { get; set; }
        public virtual DbSet<t_carpeta_estado> t_carpeta_estado { get; set; }
        public virtual DbSet<t_documento> t_documento { get; set; }
        public virtual DbSet<t_documento_tercero> t_documento_tercero { get; set; }
        public virtual DbSet<t_listpdf> t_listpdf { get; set; }
        public virtual DbSet<t_lote> t_lote { get; set; }
        public virtual DbSet<t_lpdf_hc> t_lpdf_hc { get; set; }
        public virtual DbSet<t_metadata> t_metadata { get; set; }
        public virtual DbSet<t_tercero> t_tercero { get; set; }
        public virtual DbSet<p_formato> p_formato { get; set; }
        public virtual DbSet<t_documento_resp> t_documento_resp { get; set; }
        public virtual DbSet<vw_prod_diario> vw_prod_diario { get; set; }
    }
}
