//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_formato
    {
        public int id { get; set; }
        public int id_proyecto { get; set; }
        public string hc_titulo1 { get; set; }
        public string hc_titulo2 { get; set; }
        public string hc_titulo3 { get; set; }
        public string hc_cal_codigo { get; set; }
        public string hc_cal_version { get; set; }
        public string hc_cal_fecha { get; set; }
        public string hc_nota1 { get; set; }
        public string hc_nota2 { get; set; }
        public string rc_titulo1 { get; set; }
        public string rc_titulo2 { get; set; }
        public string rc_titulo3 { get; set; }
        public string rc_cal_codigo { get; set; }
        public string rc_cal_version { get; set; }
        public string rc_cal_fecha { get; set; }
        public Nullable<int> rc_marco_legal { get; set; }
        public Nullable<System.DateTime> fecha_inicial_defecto { get; set; }
        public string fi_cal_codigo { get; set; }
        public string fi_cal_version { get; set; }
        public string fi_cal_fecha { get; set; }
        public string fi_titulo1 { get; set; }
        public string fi_titulo2 { get; set; }
        public string fi_titulo3 { get; set; }
        public string fi_objeto { get; set; }
        public string fi_elaboradox { get; set; }
        public string fi_elaboradox_cargo { get; set; }
        public string fi_entregadox { get; set; }
        public string fi_entregadox_cargo { get; set; }
        public string fi_recibidox { get; set; }
        public string fi_recibidox_cargo { get; set; }
        public string fi_lugar { get; set; }
        public string fi_fecha { get; set; }
        public string cj_titulo1 { get; set; }
        public string cj_titulo2 { get; set; }
        public string cj_titulo3 { get; set; }
        public string cj_cal_codigo { get; set; }
        public string cj_cal_version { get; set; }
        public string cj_cal_fecha { get; set; }
    
        public virtual p_proyecto p_proyecto { get; set; }
    }
}
