//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class p_proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_proyecto()
        {
            this.p_usuario_perfil = new HashSet<p_usuario_perfil>();
            this.t_lote = new HashSet<t_lote>();
            this.p_recurso = new HashSet<p_recurso>();
            this.t_listpdf = new HashSet<t_listpdf>();
            this.t_lpdf_hc = new HashSet<t_lpdf_hc>();
            this.p_formato = new HashSet<p_formato>();
        }

        public IEnumerable<int> id_empresas { get; set; }
        public int id { get; set; }
        public string nom_proyecto { get; set; }
        public int id_empresa { get; set; }
        public int activo { get; set; }
        public string ruta_proyecto { get; set; }
        public string extension { get; set; }
        public Nullable<int> meta_diaria { get; set; }
        public string ruta_salida { get; set; }
        public string ruta_reportes { get; set; }
        public string ruta_firma_entrada { get; set; }
        public string ruta_firma_salida { get; set; }
        public string ruta_servidor { get; set; }
        public Nullable<int> nivel_ocr { get; set; }
    
        public virtual p_estado p_estado { get; set; }
        public virtual p_organizacion p_organizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_usuario_perfil> p_usuario_perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_lote> t_lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_recurso> p_recurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_listpdf> t_listpdf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_lpdf_hc> t_lpdf_hc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_formato> p_formato { get; set; }
    }
}
