//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class p_recurso
    {
        public int id { get; set; }
        public int id_proyecto { get; set; }
        public string nom_recurso { get; set; }
        public string proc_ocr { get; set; }
        public string proc_pdfa { get; set; }
        public string auditoria { get; set; }
        public string ruta_pdf { get; set; }
        public string nom_carpeta { get; set; }
        public int activo { get; set; }
        public string proc_hc { get; set; }
        public string ruta_s3 { get; set; }

        public virtual p_estado p_estado { get; set; }
        public virtual p_proyecto p_proyecto { get; set; }
        
        public IEnumerable<int> id_proyectos { get; set; }
    }
}
