//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_subserie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_subserie()
        {
            this.p_tipodoc = new HashSet<p_tipodoc>();
            this.t_lote = new HashSet<t_lote>();
        }
    
        public int id { get; set; }
        public int id_serie { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> pag_defecto { get; set; }
    
        public virtual p_serie p_serie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_tipodoc> p_tipodoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_lote> t_lote { get; set; }
    }
}
