//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_tipoitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_tipoitem()
        {
            this.p_tiporesp = new HashSet<p_tiporesp>();
            this.t_documento_resp = new HashSet<t_documento_resp>();
        }
    
        public int id { get; set; }
        public int id_tipo { get; set; }
        public string type { get; set; }
        public string descripcion { get; set; }
        public int requerido { get; set; }
        public int orden { get; set; }
        public int activo { get; set; }
    
        public virtual p_tipodoc p_tipodoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_tiporesp> p_tiporesp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_documento_resp> t_documento_resp { get; set; }
        public IEnumerable<p_tiporesp> resps { get; set; }
    }
}
