//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_usuario_perfil
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_proyecto { get; set; }
        public int superadmin { get; set; }
        public int web_admin { get; set; }
        public int web_consulta { get; set; }
        public int loc_admin { get; set; }
        public int loc_index { get; set; }
        public int loc_calidad { get; set; }
        public int loc_consulta { get; set; }
        public int telemetria { get; set; }
    
        public virtual p_proyecto p_proyecto { get; set; }
        public virtual p_usuario p_usuario { get; set; }
    }
}
