//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_borrar_archivos
    {
        public int id { get; set; }
        public string ruta { get; set; }
        public string nom_archivo { get; set; }
        public string borrado { get; set; }
    }
}
