//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_carpeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_carpeta()
        {
            this.t_carpeta_estado = new HashSet<t_carpeta_estado>();
            this.t_documento = new HashSet<t_documento>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_lote { get; set; }
        public string nro_expediente { get; set; }
        public string nom_expediente { get; set; }
        public string nro_caja { get; set; }
        public Nullable<int> nro_carpeta { get; set; }
        public Nullable<int> paginas { get; set; }
        public Nullable<System.DateTime> fecha_expediente_ini { get; set; }
        public Nullable<System.DateTime> fecha_expediente_fin { get; set; }
        public Nullable<int> total_folios { get; set; }
        public Nullable<int> id_tercero { get; set; }
        public int ejecucion { get; set; }
        public string estado { get; set; }
        public Nullable<int> idusr_asignado { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<bool> exp_ocr { get; set; }
        public Nullable<bool> exp_pdfa { get; set; }
        public Nullable<bool> exp_firma { get; set; }
        public Nullable<int> idusr_control { get; set; }
        public string hc_inicio { get; set; }
        public string hc_fin { get; set; }
        public string tomo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_carpeta_estado> t_carpeta_estado { get; set; }
        public virtual t_tercero t_tercero { get; set; }
        public virtual t_lote t_lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_documento> t_documento { get; set; }
        public virtual p_usuario p_usuario { get; set; }
        public virtual p_usuario p_usuario1 { get; set; }
        public virtual p_usuario p_usuario2 { get; set; }
    }
}
