//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_carpeta_estado
    {
        public int id { get; set; }
        public int id_carpeta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string fase { get; set; }
        public int rechazado { get; set; }
        public System.DateTime fecha_estado { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> modificacion_pdf { get; set; }
    
        public virtual t_carpeta t_carpeta { get; set; }
        public virtual p_usuario p_usuario { get; set; }
    }
}
