//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_documento()
        {
            this.t_documento_tercero = new HashSet<t_documento_tercero>();
            this.t_documento_resp = new HashSet<t_documento_resp>();
        }
    
        public int id { get; set; }
        public int id_carpeta { get; set; }
        public Nullable<int> id_tipodoc { get; set; }
        public Nullable<int> pag_ini { get; set; }
        public Nullable<int> pag_fin { get; set; }
        public string ruta_docpdf { get; set; }
        public Nullable<bool> doc_ocr { get; set; }
        public Nullable<bool> doc_pdfa { get; set; }
        public Nullable<bool> doc_firma { get; set; }
        public Nullable<int> folio_ini { get; set; }
        public Nullable<int> folio_fin { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public bool requiere_seleccion { get; set; }
        public string item { get; set; }
    
        public virtual p_tipodoc p_tipodoc { get; set; }
        public virtual t_carpeta t_carpeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_documento_tercero> t_documento_tercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_documento_resp> t_documento_resp { get; set; }
    }
}
