//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_metadata
    {
        public int id { get; set; }
        public string direccion_admin { get; set; }
        public string oficina { get; set; }
        public string serie { get; set; }
        public string subserie { get; set; }
        public Nullable<int> identificador { get; set; }
        public string expediente { get; set; }
        public string tomo { get; set; }
        public Nullable<System.DateTime> fecha_inicial { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public Nullable<int> folio_ini { get; set; }
        public Nullable<int> folio_fin { get; set; }
        public Nullable<int> imagenes { get; set; }
        public string observaciones { get; set; }
        public string notas { get; set; }
        public Nullable<System.DateTime> captura { get; set; }
        public Nullable<System.DateTime> calidad { get; set; }
        public string nom_archivo { get; set; }
        public int id_recurso { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string ruta_final { get; set; }
        public string directorio { get; set; }
        public string archivo_salida { get; set; }
    
        public virtual t_metadata t_metadata1 { get; set; }
        public virtual t_metadata t_metadata2 { get; set; }
    }
}
