//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admindx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_prod_diario
    {
        public Nullable<int> id_proyecto { get; set; }
        public int id_carpeta { get; set; }
        public string nom_lote { get; set; }
        public string nro_caja { get; set; }
        public string nro_expediente { get; set; }
        public Nullable<System.DateTime> f_asignacion { get; set; }
        public string asignado { get; set; }
        public Nullable<System.DateTime> f_realizado { get; set; }
        public string Realizado { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> nro_carpeta { get; set; }
        public string hc_inicio { get; set; }
        public string hc_fin { get; set; }
        public string tomo { get; set; }
        public Nullable<int> folio_inicial { get; set; }
        public Nullable<int> folio_final { get; set; }
        public Nullable<int> registros { get; set; }
        public Nullable<int> folio_total { get; set; }
    }
}
